{% set name = "google-auth-oauthlib" %}
{% set version = "0.4.2" %}
{% set sha256 = "65b65bc39ad8cab15039b35e5898455d3d66296d0584d96fe0e79d67d04c51d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - google-oauthlib-tool = google_auth_oauthlib.tool.__main__:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - google-auth
    - requests-oauthlib >=0.7.0
    - click

test:
  requires:
    - python
    - pip
  imports:
    - google_auth_oauthlib
  commands:
    - google-oauthlib-tool --help
    - python -m pip check

about:
  home: https://github.com/googleapis/google-auth-library-python-oauthlib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Authentication Library, oauthlib integration with google-auth
  description: This library provides oauthlib integration with google-auth.
  doc_url: http://google-auth-oauthlib.readthedocs.io/en/latest/
  dev_url: https://github.com/googleapis/google-auth-library-python-oauthlib

extra:
  recipe-maintainers:
    - cpcloud
    - jreback
    - leahecole
    - parthea
    - tswast
