travis:
  secure:
    BINSTAR_TOKEN: bUF21kDOuagFl33sz5YQUZn6ZBr6o3uEM5HhrWNt7OIqMIGvI/exd9HDMkoGYzE9zk1MmVaFbpv4HQnAg2ZkrasoAMrfQcwb3PIgEj4jAXllBB9IyVEHUjKfqaeHWZEcECioriTiP4QHt1F/ipoI5y/YLflvYzXx6fhao/NK6E0MVKoW21na9GotnnqzBzQktYryjGB7AZ9UnVqkWFtxH8JkA95uyvgUbbl5dlExehJ5mDAUA2MkecvcixohkziRIppVI6Otn1MnzVU2RBC/T34Ja3x2N+mGFe0+YXENmbXEGohVckXEFJ/NFTa5sK9X965GhRCAeRfjxdzUCd9subkPh1JxxNOVOvmBgyMrBn0A5e/f30H1qNnMqrohWcwUghsH0xiROwzd6R8zgCycISr46bdEJJP8b/mEVRR5EL6OGz5jxsw8ynCKtd65nFoqDtopgiIrC/tf8PYksUParXMGqiYSsxgYUUbcc2OWXHi4Ccstkw1Co29SZ2rLA5Xxaycxgq+xbVWhohIIxJkWTlswpsD1R2biFY/ijQb77FQQgbUl0WBCt6+Nq42RJWj/t4ZL/KW1w2MAgzZx1L9jOaMMsoxk3GdW+wxwhtE9Xujt6L36uq4kj6FN9Tq5Kf59nVGZPlSbMhHZ4dJBamlfoL9/KZOK+alEsrDpZSkyET4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
